#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

enum custom_keycodes
{
    LT1_LGUI_A = SAFE_RANGE
};

enum LAYERS
{
    L_DEFAULT = 0,
    L_ADJUST
};

// USER CUSTOMISATION
#define KEY_MODIFIER KC_LGUI
#define KEY_KC "a"
//*****************

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [L_DEFAULT] = LAYOUT(LT1_LGUI_A, LGUI(KC_C), LGUI(KC_V)),
    [L_ADJUST] = LAYOUT(KC_TRNS, RGB_HUD, RGB_TOG)};

// Based on https://thomasbaart.nl/2018/12/09/qmk-basics-tap-and-hold-actions/
bool process_record_user(uint16_t keycode, keyrecord_t *record)
{
    static uint16_t my_hash_timer;
    switch (keycode)
    {
    case LT1_LGUI_A:
        if (record->event.pressed)
        {
            my_hash_timer = timer_read();
            // Turn on layer 1
            layer_on(L_ADJUST);
        }
        else
        {
            // Turn off layer 1
            layer_off(L_ADJUST);
            if (timer_elapsed(my_hash_timer) < TAPPING_TERM)
            {
                // If it's a tap, register the modifier
                register_code(KEY_MODIFIER);
                // send the key
                SEND_STRING(KEY_KC); // Change the character(s) to be sent on tap here
                // and unregister the modifier
                unregister_code(KEY_MODIFIER);
            }
        }
        return false; // We handled this keypress
    }
    return true; // We didn't handle other keypresses
}
